/*
 * arcsec.h - C interface to the arcsec plate solver (libarcsec).
 *
 * Generated by cbindgen from libarcsec/src; do not edit by hand.
 * Documentation: libarcsec/README.md and https://cruzzil.github.io/arcsec/c-library/
 *
 * SPDX-License-Identifier: MIT
 */

#ifndef ARCSEC_H
#define ARCSEC_H

#include <stddef.h>
#include <stdint.h>
/* Link against libarcsec (pkg-config: arcsec). Every function is thread-safe
 * unless its documentation says otherwise; see README.md for the threading,
 * ownership and versioning rules. */

/**
 * Version of the C ABI this library implements.
 *
 * It changes only when a change would break a program compiled against an older
 * header: a function removed or its signature changed, a struct field moved or
 * retyped. Adding functions, adding fields at the end of a struct (callers set
 * `struct_size`), and adding status codes or enum values do not change it.
 */
#define ARCSEC_ABI_VERSION 1

/**
 * `arcsec_image::flags`: row 0 of the buffer is the *top* of the picture (the
 * last row of a FITS image). Without it, row 0 is FITS row 1, the bottom, as
 * CFITSIO reads it and Siril keeps it.
 */
#define ARCSEC_IMAGE_TOP_DOWN 1

/**
 * `arcsec_solve_options::method`: ASTAP-style four-star quads (the default).
 */
#define ARCSEC_METHOD_QUADS 0

/**
 * `arcsec_solve_options::method`: three-star triangles.
 */
#define ARCSEC_METHOD_TETRA 1

/**
 * Highest SIP order an `arcsec_wcs` can hold. arcsec fits order 3 today; the
 * arrays are sized for more so that higher orders need no ABI change.
 */
#define ARCSEC_SIP_MAX_ORDER 9

/**
 * Side of the SIP coefficient arrays: `ARCSEC_SIP_MAX_ORDER + 1`.
 */
#define ARCSEC_SIP_SIZE (ARCSEC_SIP_MAX_ORDER + 1)

/**
 * What a call did. The solve codes have the values of the `arcsec` (and ASTAP)
 * command-line exit codes, so a host that already handles those can map them
 * one to one.
 */
typedef enum arcsec_status {
    /**
     * Success; for a solve, a verified solution.
     */
    ARCSEC_OK = 0,
    /**
     * The search finished without a verified solution (CLI exit 1).
     */
    ARCSEC_NO_SOLUTION = 1,
    /**
     * Too few stars were detected to solve (CLI exit 2).
     */
    ARCSEC_INSUFFICIENT_STARS = 2,
    /**
     * The image file could not be read, or is not FITS, XISF or ASDF (CLI exit 16).
     */
    ARCSEC_FILE_ERROR = 16,
    /**
     * The star database or blind index was not found (CLI exit 32).
     */
    ARCSEC_DATABASE_NOT_FOUND = 32,
    /**
     * A star database or index file could not be read (CLI exit 33).
     */
    ARCSEC_DATABASE_ERROR = 33,
    /**
     * An argument was NULL, out of range or inconsistent, or a struct's
     * `struct_size` was not set.
     */
    ARCSEC_INVALID_ARGUMENT = 100,
    /**
     * The solve was cancelled (`arcsec_solver_cancel` or the options'
     * cancel callback).
     */
    ARCSEC_CANCELLED = 101,
    /**
     * The solver handle is already running a solve on another thread.
     */
    ARCSEC_BUSY = 102,
    /**
     * A bug in arcsec: an internal error (a Rust panic) was caught at the library
     * boundary. The library is still usable; please report it with the message
     * from `arcsec_last_error`.
     */
    ARCSEC_INTERNAL_ERROR = 199,
} arcsec_status;

/**
 * Sample types an `arcsec_image` can hold, in the machine's native byte order.
 */
typedef enum arcsec_pixel_type {
    /**
     * `uint8_t`.
     */
    ARCSEC_PIXEL_U8 = 1,
    /**
     * `uint16_t` (Siril's `WORD`, most camera data).
     */
    ARCSEC_PIXEL_U16 = 2,
    /**
     * `int16_t` (FITS BITPIX 16 without BZERO applied).
     */
    ARCSEC_PIXEL_I16 = 3,
    /**
     * `uint32_t`.
     */
    ARCSEC_PIXEL_U32 = 4,
    /**
     * `int32_t`.
     */
    ARCSEC_PIXEL_I32 = 5,
    /**
     * `float`; any range (data normalised to 0..1 is fine).
     */
    ARCSEC_PIXEL_F32 = 6,
    /**
     * `double`.
     */
    ARCSEC_PIXEL_F64 = 7,
} arcsec_pixel_type;

/**
 * Message severities, most severe first. `arcsec_set_log_callback` passes
 * messages at or above the level it is given.
 */
typedef enum arcsec_log_level {
    /**
     * No messages.
     */
    ARCSEC_LOG_OFF = 0,
    /**
     * Errors: internal errors caught at the library boundary.
     */
    ARCSEC_LOG_ERROR = 1,
    /**
     * Warnings: a blind index that could not be read, a fallback to the hint.
     */
    ARCSEC_LOG_WARN = 2,
    /**
     * Progress: stars found, databases chosen, search positions, the solution.
     * What `arcsec --progress` prints.
     */
    ARCSEC_LOG_INFO = 3,
    /**
     * Diagnostics.
     */
    ARCSEC_LOG_DEBUG = 4,
    /**
     * Detailed diagnostics.
     */
    ARCSEC_LOG_TRACE = 5,
} arcsec_log_level;

/**
 * A plate solution, owned by the library. Read it with the `arcsec_result_*`
 * functions and release it with `arcsec_result_free`. Immutable, so it may be
 * read from several threads at once.
 */
typedef struct arcsec_result arcsec_result;

/**
 * A solver: the handle a solve runs on, and through which it can be cancelled.
 *
 * It holds no catalogue or image data between solves; one per thread that
 * solves is the intended use. A handle runs one solve at a time: a second
 * `arcsec_solve` on it from another thread, while one is running, returns
 * `ARCSEC_BUSY` at once rather than waiting. `arcsec_solver_cancel` may be
 * called from any thread at any time.
 */
typedef struct arcsec_solver arcsec_solver;

/**
 * An image in the caller's memory. Not copied by the caller: arcsec reads it
 * during the call and keeps no pointer to it afterwards.
 *
 * Zero it, set `struct_size = sizeof(arcsec_image)`, then fill in the fields.
 * Multi-channel images are averaged to one channel before solving.
 *
 * The pixel at column `x`, row `y` of channel `c` is read from
 * `plane(c) + y * row_stride + x * sizeof(sample)`, where `plane(c)` is
 * `planes[c]` if `planes` is set, else `data + c * plane_stride`. Strides are in
 * bytes; 0 means tightly packed. Pointers need no particular alignment.
 */
typedef struct arcsec_image {
    /**
     * `sizeof(arcsec_image)`.
     */
    size_t struct_size;
    /**
     * The first sample of channel 0, when `planes` is NULL.
     */
    const void *data;
    /**
     * Optional: `channels` pointers, one per channel plane (Siril's `pdata`).
     * Takes precedence over `data` and `plane_stride`.
     */
    const void *const *planes;
    /**
     * Sample type: one of `arcsec_pixel_type`.
     */
    uint32_t pixel_type;
    /**
     * Columns.
     */
    uint32_t width;
    /**
     * Rows.
     */
    uint32_t height;
    /**
     * Channels (planes); 0 is taken as 1.
     */
    uint32_t channels;
    /**
     * Bytes from one row to the next; 0 = `width * sizeof(sample)`.
     */
    size_t row_stride;
    /**
     * Bytes from one plane to the next (ignored with `planes`); 0 =
     * `height * row_stride`.
     */
    size_t plane_stride;
    /**
     * `ARCSEC_IMAGE_*` flags.
     */
    uint32_t flags;
    /**
     * Reserved; set to 0.
     */
    uint32_t reserved;
} arcsec_image;

/**
 * What `arcsec_analyse` found. Set `struct_size` before the call.
 */
typedef struct arcsec_analysis {
    /**
     * `sizeof(arcsec_analysis)`, set by the caller.
     */
    size_t struct_size;
    /**
     * Stars found.
     */
    uint64_t star_count;
    /**
     * Median HFD of those stars, pixels; 0 if there are none.
     */
    double hfd_median;
    /**
     * Background level, in the units of the (normalised) pixels.
     */
    double background;
    /**
     * Background noise (standard deviation), same units.
     */
    double noise;
} arcsec_analysis;

/**
 * A star measured by `arcsec_analyse`.
 */
typedef struct arcsec_star {
    /**
     * Centroid column, 1-based FITS pixels.
     */
    double x;
    /**
     * Centroid row, 1-based FITS pixels.
     */
    double y;
    /**
     * Half-flux diameter, pixels.
     */
    double hfd;
    /**
     * Signal-to-noise ratio.
     */
    double snr;
    /**
     * Background-subtracted flux, in the units of the (normalised) pixels.
     */
    double flux;
} arcsec_star;

/**
 * Log callback: `level` is an `arcsec_log_level`, `message` a NUL-terminated
 * UTF-8 line without a trailing newline, valid only during the call.
 *
 * It may be called from any thread, including the solver's worker threads and
 * several at once, so it must be thread-safe. It must not call
 * `arcsec_set_log_callback`, throw or `longjmp`.
 */
typedef void (*arcsec_log_fn)(void *user, int level, const char *message);

/**
 * Cancellation callback: return nonzero to stop the solve.
 *
 * Called often (at every search position) and from the solver's worker threads,
 * possibly several at once, so it must be fast and thread-safe — reading a flag
 * is ideal. It must not call back into arcsec, throw or `longjmp`.
 */
typedef int (*arcsec_cancel_fn)(void *user);

/**
 * Progress callback: `fraction` in [0, 1] through the current `stage`, or -1
 * when the stage's extent is unknown. Stages: "detecting stars", "searching"
 * (the fraction of search positions within the radius started so far; a solve
 * usually ends well before 1), "blind index". `stage` is a static string.
 *
 * Called from the solver's worker threads, possibly several at once, and at most
 * a few hundred times per solve, so it must be thread-safe. It must not call back
 * into arcsec, throw or `longjmp`.
 */
typedef void (*arcsec_progress_fn)(void *user, double fraction, const char *stage);

/**
 * How to solve. Initialise with `arcsec_solve_options_init`, which sets
 * `struct_size` and every default, then change what you need. Strings are
 * UTF-8, NUL-terminated, read during the call only, and NULL (or "") for unset.
 */
typedef struct arcsec_solve_options {
    /**
     * `sizeof(arcsec_solve_options)`; set by the init function.
     */
    size_t struct_size;
    /**
     * Nonzero: `ra_deg`/`dec_deg` are the approximate image centre. Zero: no
     * hint (from these fields; the FITS header may still give one).
     */
    int32_t has_hint;
    /**
     * Approximate right ascension of the image centre, degrees.
     */
    double ra_deg;
    /**
     * Approximate declination of the image centre, degrees.
     */
    double dec_deg;
    /**
     * How far from the hint to search, degrees. Default 180 (the whole sky). 0
     * tries the hint position only.
     */
    double search_radius_deg;
    /**
     * Field of view along the image *height*, degrees (ASTAP's `-fov`); 0 if
     * unknown. Takes precedence over `pixel_scale_arcsec`.
     */
    double fov_deg;
    /**
     * Pixel scale of the image as passed (unbinned), arcseconds per pixel; 0 if
     * unknown. With neither this nor `fov_deg` nor header optics, 1″/px is
     * assumed, which is usually wrong: pass the scale if you know it.
     */
    double pixel_scale_arcsec;
    /**
     * Optional FITS header text: 80-character cards run together (as CFITSIO's
     * `fits_hdr2str` writes them) or one per line. Used only for what the fields
     * above leave unset: the hint from RA/DEC (or CRVAL1/2), the pixel scale from
     * FOCALLEN, XPIXSZ and XBINNING — the keywords the CLI reads from a file.
     */
    const char *fits_header;
    /**
     * Star database directory. NULL: the directory `arcsec catalog install`
     * uses (see `arcsec_default_catalog_dir`) if it holds a database,
     * else the working directory.
     */
    const char *catalog_dir;
    /**
     * Star database name (`"d50"`, `"g05"`, ...). NULL: the densest installed
     * database whose range suits the field size.
     */
    const char *database;
    /**
     * Blind index to use: an arcsec `.arcsecix` file, a directory holding one,
     * or a directory of Astrometry.net `index-*.fits` files; NULL for none (but
     * see `auto_index`). Without a hint it is tried first and solves blind. With
     * one, it is a fallback: the solver first searches a few fields round the
     * hint (five fields, at least 1°, within `search_radius_deg`) and consults
     * the index only if that finds nothing — unless `index_first` is set.
     */
    const char *index_path;
    /**
     * Nonzero: with a hint, try `index_path` before searching round the hint, as
     * `arcsec --index` does. Default 0.
     */
    int32_t index_first;
    /**
     * Nonzero (default): when the search radius is wide (at least 10° and more
     * than five fields), consult an arcsec index installed in the catalogue
     * directory, as the CLI does. Zero: never use an index not named in
     * `index_path`.
     */
    int32_t auto_index;
    /**
     * SIP distortion order wanted: 0 or 1 (default) for a linear solution, 2 or
     * more to fit SIP polynomials. arcsec currently fits order 3 whatever the
     * value, and returns them only when the distortion is significant; the
     * result's `sip_order` says what was fitted.
     */
    int32_t sip_order;
    /**
     * Most image stars to use. Default 500.
     */
    uint32_t max_stars;
    /**
     * Binning factor before solving; 0 (default) chooses one from the scale.
     */
    uint32_t downsample;
    /**
     * Worker threads for this solve; 0 (default) uses one per core.
     */
    uint32_t threads;
    /**
     * `ARCSEC_METHOD_QUADS` (default) or `ARCSEC_METHOD_TETRA`.
     */
    uint32_t method;
    /**
     * Nonzero: read a catalogue window twice the field at every search position
     * (ASTAP's `-speed slow`). Slower; helps fields with many stars.
     */
    int32_t slow;
    /**
     * Nonzero: even out a raw one-shot-colour (Bayer) mosaic first (ASTAP's
     * `-check y`). Ignored for multi-channel images.
     */
    int32_t check_pattern;
    /**
     * Pattern-matching tolerance. Default 0.007.
     */
    double quad_tolerance;
    /**
     * Smallest star to use, half-flux diameter in arcseconds. Default 1.5.
     */
    double hfd_min_arcsec;
    /**
     * Optional cancellation callback, polled during the solve.
     */
    arcsec_cancel_fn cancel;
    /**
     * Passed to `cancel`.
     */
    void *cancel_user;
    /**
     * Optional progress callback.
     */
    arcsec_progress_fn progress;
    /**
     * Passed to `progress`.
     */
    void *progress_user;
} arcsec_solve_options;

/**
 * The WCS of a solution, as FITS keywords. Pixel coordinates are 1-based FITS
 * pixels of the image as passed (unbinned), with row 1 the first row in FITS
 * order (see `ARCSEC_IMAGE_TOP_DOWN`).
 *
 * Set `struct_size = sizeof(arcsec_wcs)` before calling `arcsec_result_wcs`.
 */
typedef struct arcsec_wcs {
    /**
     * `sizeof(arcsec_wcs)`, set by the caller.
     */
    size_t struct_size;
    /**
     * CRVAL1: right ascension of the reference pixel, degrees.
     */
    double crval1;
    /**
     * CRVAL2: declination of the reference pixel, degrees.
     */
    double crval2;
    /**
     * CRPIX1: reference pixel column (the image centre).
     */
    double crpix1;
    /**
     * CRPIX2: reference pixel row.
     */
    double crpix2;
    /**
     * CD1_1, degrees per pixel.
     */
    double cd1_1;
    /**
     * CD1_2, degrees per pixel.
     */
    double cd1_2;
    /**
     * CD2_1, degrees per pixel.
     */
    double cd2_1;
    /**
     * CD2_2, degrees per pixel.
     */
    double cd2_2;
    /**
     * CDELT1, degrees per pixel: negative, as FITS has it for an unmirrored image.
     */
    double cdelt1;
    /**
     * CDELT2, degrees per pixel.
     */
    double cdelt2;
    /**
     * CROTA2, degrees.
     */
    double crota2;
    /**
     * Pixel scale, arcseconds per pixel.
     */
    double pixel_scale_arcsec;
    /**
     * RMS residual of the matched stars, arcseconds.
     */
    double rms_arcsec;
    /**
     * Stars matched to the catalogue in the final verification.
     */
    uint32_t matched_stars;
    /**
     * Nonzero if the image is mirrored (det CD > 0).
     */
    int32_t mirrored;
    /**
     * Order of the SIP polynomials below; 0 if there are none.
     */
    int32_t sip_order;
    /**
     * Reserved; 0.
     */
    int32_t reserved;
    /**
     * SIP `A_p_q` at `sip_a[p][q]` (p + q ≤ `sip_order`, others 0): pixel → sky
     * correction along x, in pixels, applied to offsets from CRPIX.
     */
    double sip_a[ARCSEC_SIP_SIZE][ARCSEC_SIP_SIZE];
    /**
     * SIP `B_p_q`: pixel → sky correction along y.
     */
    double sip_b[ARCSEC_SIP_SIZE][ARCSEC_SIP_SIZE];
    /**
     * SIP `AP_p_q`: sky → pixel correction along x.
     */
    double sip_ap[ARCSEC_SIP_SIZE][ARCSEC_SIP_SIZE];
    /**
     * SIP `BP_p_q`: sky → pixel correction along y.
     */
    double sip_bp[ARCSEC_SIP_SIZE][ARCSEC_SIP_SIZE];
} arcsec_wcs;

/**
 * How a solve went, beyond the WCS. Set `struct_size` before the call.
 */
typedef struct arcsec_solve_info {
    /**
     * `sizeof(arcsec_solve_info)`, set by the caller.
     */
    size_t struct_size;
    /**
     * Binning factor the image was solved at.
     */
    uint32_t binning;
    /**
     * Pattern matches found before outlier rejection.
     */
    uint32_t raw_matches;
    /**
     * Distance from the hint to the solved centre, degrees.
     */
    double search_distance_deg;
    /**
     * Faintest catalogue magnitude used.
     */
    double mag_limit;
    /**
     * Wall-clock time of the solve, seconds.
     */
    double elapsed_seconds;
    /**
     * Nonzero if an Astrometry.net index estimated the position first.
     */
    int32_t has_index_estimate;
    /**
     * Reserved; 0.
     */
    int32_t reserved;
    /**
     * That estimate's right ascension, degrees.
     */
    double index_ra_deg;
    /**
     * That estimate's declination, degrees.
     */
    double index_dec_deg;
} arcsec_solve_info;

/**
 * A detected star and the catalogue star it was matched to.
 */
typedef struct arcsec_matched_star {
    /**
     * Column, 1-based FITS pixels of the unbinned image.
     */
    double x;
    /**
     * Row, 1-based FITS pixels.
     */
    double y;
    /**
     * Catalogue right ascension, degrees.
     */
    double ra_deg;
    /**
     * Catalogue declination, degrees.
     */
    double dec_deg;
} arcsec_matched_star;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * The library's version string, e.g. `"0.4.0"` (the arcsec release it was built
 * from). Static; never NULL; do not free.
 */
const char *arcsec_version(void);

/**
 * The ABI version the library implements (`ARCSEC_ABI_VERSION` when it was
 * built). Compare it with the `ARCSEC_ABI_VERSION` your program was compiled
 * with: a different value means the header and the library do not match.
 */
uint32_t arcsec_abi_version(void);

/**
 * Detect and measure the stars of an image without solving it, as `arcsec
 * --analyse` does: their number and median HFD (ASTAP's `HFD_MEDIAN` and
 * `STARS`), and optionally the stars themselves.
 *
 * `snr_min` is the smallest signal-to-noise ratio counted (0 for ASTAP's 30);
 * `max_stars` the number of stars detection aims for (0 for 500). Up to
 * `stars_capacity` stars are copied to `stars` (which may be NULL when the
 * capacity is 0), in detection order; `out->star_count` is the full number.
 *
 * # Safety
 *
 * `image` as for `arcsec_solve`; `out` must be NULL or point to
 * `out->struct_size` writable bytes; `stars` must be NULL or have room for
 * `stars_capacity` elements.
 */
enum arcsec_status arcsec_analyse(const struct arcsec_image *image,
                                  double snr_min,
                                  uint32_t max_stars,
                                  struct arcsec_analysis *out,
                                  struct arcsec_star *stars,
                                  size_t stars_capacity);

/**
 * Write the directory `arcsec catalog install` puts catalogues in
 * (`$ARCSEC_CATALOG_DIR`, else e.g. `~/.local/share/arcsec/catalogs`) into
 * `buf`, as `snprintf` does: at most `len - 1` bytes and a NUL. Returns the
 * path's full length, so a value `>= len` means `buf` was too small (call with
 * `len` 0 to size it). The directory may not exist.
 *
 * # Safety
 *
 * `buf` must be NULL or point to `len` writable bytes.
 */
size_t arcsec_default_catalog_dir(char *buf, size_t len);

/**
 * Like `arcsec_default_catalog_dir`, but the directory a solve uses when
 * `catalog_dir` is NULL: the catalogue directory if it holds a star database,
 * else the working directory (`"."`).
 *
 * # Safety
 *
 * As `arcsec_default_catalog_dir`.
 */
size_t arcsec_default_database_dir(char *buf, size_t len);

/**
 * Whether `dir` (NULL: the default database directory) holds a star database
 * arcsec can solve with: 1 if so, 0 if not, -1 for a bad argument.
 *
 * # Safety
 *
 * `dir` must be NULL or a NUL-terminated string.
 */
int arcsec_has_star_database(const char *dir);

/**
 * Choose the star database for a field `fov_deg` degrees across (the longer
 * side) from those in `dir` (NULL: the default database directory), as a solve
 * does when `database` is NULL, and write its name (e.g. `"d50"`) into `buf` as
 * `arcsec_default_catalog_dir` does. Returns the name's length, 0 if `dir`
 * holds no database (or on a bad argument; see `arcsec_last_error`).
 *
 * # Safety
 *
 * `dir` must be NULL or a NUL-terminated string; `buf` NULL or `len` writable
 * bytes.
 */
size_t arcsec_select_database(const char *dir, double fov_deg, char *buf, size_t len);

/**
 * Whether a blind index is available at `path` (NULL: the default catalogue
 * directory): 1 for an arcsec index (`*.arcsecix`, the file or one in the
 * directory), 2 for Astrometry.net `index-*.fits` files, 0 for none, -1 for a
 * bad argument. With an index, a solve needs no position hint.
 *
 * # Safety
 *
 * `path` must be NULL or a NUL-terminated string.
 */
int arcsec_has_blind_index(const char *path);

/**
 * The message describing the most recent call on this thread that failed (did
 * not return `ARCSEC_OK`, or returned NULL or an error value). An empty string
 * if none has. Successful calls leave it unchanged.
 *
 * The string belongs to the library and stays valid until the next failing
 * call on the same thread; copy it if you need it longer. Never NULL.
 */
const char *arcsec_last_error(void);

/**
 * A short static description of a status code (e.g. "no solution"). Unknown
 * values give "unknown status". Never NULL; do not free.
 */
const char *arcsec_status_string(int status);

/**
 * Send arcsec's log messages to `callback` (NULL to stop), for messages at
 * `max_level` (an `arcsec_log_level`) and more severe. Process-wide: one
 * callback serves every solver and thread, and messages from concurrent solves
 * interleave. Off until called.
 *
 * Thread-safe, but a message already being delivered may still reach the
 * previous callback just after this returns; keep the old `user` data alive
 * until the solves that might log to it have finished.
 *
 * # Safety
 *
 * `callback` must be NULL or a function safe to call from any thread with
 * `user`, as described on `arcsec_log_fn`.
 */
void arcsec_set_log_callback(arcsec_log_fn callback, void *user, int max_level);

/**
 * Fill `opts` with the defaults (those of the `arcsec` command line) and set its
 * `struct_size`. Returns `ARCSEC_INVALID_ARGUMENT` if `opts` is NULL.
 *
 * # Safety
 *
 * `opts` must be NULL or point to a writable `arcsec_solve_options`.
 */
enum arcsec_status arcsec_solve_options_init(struct arcsec_solve_options *opts);

/**
 * Copy the solution's WCS into `out`, whose `struct_size` you have set.
 *
 * # Safety
 *
 * `result` must be NULL or a live result; `out` must be NULL or point to
 * `out->struct_size` writable bytes.
 */
enum arcsec_status arcsec_result_wcs(const struct arcsec_result *result, struct arcsec_wcs *out);

/**
 * Copy facts about the solve into `out`, whose `struct_size` you have set.
 *
 * # Safety
 *
 * As `arcsec_result_wcs`.
 */
enum arcsec_status arcsec_result_info(const struct arcsec_result *result,
                                      struct arcsec_solve_info *out);

/**
 * The star database the solve used (e.g. `"d50"`), valid until the result is
 * freed. NULL if `result` is NULL.
 *
 * # Safety
 *
 * `result` must be NULL or a live result.
 */
const char *arcsec_result_database(const struct arcsec_result *result);

/**
 * Copy up to `capacity` of the matched star pairs into `out` and return how many
 * there are in all (so a call with `capacity` 0 asks for the count). `out` may
 * be NULL when `capacity` is 0. Returns 0 if `result` is NULL.
 *
 * # Safety
 *
 * `result` must be NULL or a live result; `out` must be NULL or have room for
 * `capacity` elements.
 */
size_t arcsec_result_matched_stars(const struct arcsec_result *result,
                                   struct arcsec_matched_star *out,
                                   size_t capacity);

/**
 * Map a 1-based FITS pixel to the sky (degrees, RA in [0, 360)), through the
 * solution including its SIP terms.
 *
 * # Safety
 *
 * `result` must be NULL or a live result; `ra_deg` and `dec_deg` must be NULL or
 * writable.
 */
enum arcsec_status arcsec_result_pixel_to_sky(const struct arcsec_result *result,
                                              double x,
                                              double y,
                                              double *ra_deg,
                                              double *dec_deg);

/**
 * Map a sky position (degrees) to a 1-based FITS pixel through the solution.
 * `ARCSEC_INVALID_ARGUMENT` for a position on the far side of the sky, which has
 * no pixel.
 *
 * # Safety
 *
 * As `arcsec_result_pixel_to_sky`.
 */
enum arcsec_status arcsec_result_sky_to_pixel(const struct arcsec_result *result,
                                              double ra_deg,
                                              double dec_deg,
                                              double *x,
                                              double *y);

/**
 * Write the solution as FITS header cards into `buf`, as `snprintf` does (at
 * most `len - 1` bytes and a NUL; returns the full length, so a value `>= len`
 * means `buf` was too small — call with `len` 0 to size it). The cards are
 * 80-character records run together without newlines, as CFITSIO's
 * `fits_hdr2str` makes them, ending with `END`: CTYPE1/2 (`RA---TAN`, or
 * `RA---TAN-SIP` with SIP), CUNIT1, CRPIX1/2, CRVAL1/2, CDELT1/2, CROTA1/2,
 * CD1_1..CD2_2, the SIP keywords if fitted, and PLTSOLVD — the content of the
 * `.wcs` file `arcsec` and ASTAP write, ready for wcslib's `wcspih`. Returns 0
 * if `result` is NULL.
 *
 * # Safety
 *
 * `result` must be NULL or a live result; `buf` NULL or `len` writable bytes.
 */
size_t arcsec_result_fits_header(const struct arcsec_result *result, char *buf, size_t len);

/**
 * Free a result. NULL is ignored.
 *
 * # Safety
 *
 * `result` must be NULL or a live result, not used again afterwards.
 */
void arcsec_result_free(struct arcsec_result *result);

/**
 * Create a solver. Returns NULL only if memory is exhausted. Free it with
 * `arcsec_solver_free`.
 */
struct arcsec_solver *arcsec_solver_new(void);

/**
 * Free a solver. NULL is ignored. It must not be running a solve: free it after
 * the solve call has returned (cancel it first to make that quick).
 *
 * # Safety
 *
 * `solver` must be NULL or a live solver, not used again afterwards.
 */
void arcsec_solver_free(struct arcsec_solver *solver);

/**
 * Ask the solve running on `solver` to stop. It returns `ARCSEC_CANCELLED` soon
 * after (at its next checkpoint, typically within milliseconds). Thread-safe;
 * does nothing if no solve is running, and does not affect a solve started later.
 *
 * # Safety
 *
 * `solver` must be NULL or a live solver.
 */
void arcsec_solver_cancel(const struct arcsec_solver *solver);

/**
 * Solve an image held in memory.
 *
 * On `ARCSEC_OK`, `*out` is a new result to free with `arcsec_result_free`;
 * otherwise `*out` is NULL and `arcsec_last_error` says why. `opts` may
 * be NULL for all defaults.
 *
 * Blocks until the solve ends; run it on a worker thread and cancel it from
 * another with `arcsec_solver_cancel` or the options' cancel callback.
 *
 * # Safety
 *
 * `solver` must be NULL or a live solver; `image` must be NULL or describe
 * readable memory as documented on `arcsec_image`; `opts` must be NULL or an
 * initialised options struct; `out` must be NULL or writable.
 */
enum arcsec_status arcsec_solve(const struct arcsec_solver *solver,
                                const struct arcsec_image *image,
                                const struct arcsec_solve_options *opts,
                                struct arcsec_result **out);

/**
 * Solve an image file: FITS (including compressed), XISF or ASDF, told apart by
 * content. The file's header supplies the hint and pixel scale where the
 * options (and their `fits_header`) do not, exactly as the `arcsec` command
 * line reads them. Colour images are averaged to one channel, except FITS cubes,
 * which are read as their first plane (as the CLI does).
 *
 * Results, errors and threading are as for `arcsec_solve`; an unreadable file
 * is `ARCSEC_FILE_ERROR`.
 *
 * # Safety
 *
 * `path` must be NULL or a NUL-terminated string (UTF-8; any bytes on Unix); the
 * rest as for `arcsec_solve`.
 */
enum arcsec_status arcsec_solve_file(const struct arcsec_solver *solver,
                                     const char *path,
                                     const struct arcsec_solve_options *opts,
                                     struct arcsec_result **out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ARCSEC_H */
